#!/bin/bash
curl -k "http://localhost/itnerd-git/scriptjes/warehouse"
curl -k "http://localhost/itnerd-git/scriptjes/item"
curl -k "http://localhost/itnerd-git/scriptjes/itemfingoods"
curl -k "http://localhost/itnerd-git/scriptjes/itemwhbal"
curl -k "http://localhost/itnerd-git/scriptjes/producttype"
curl -k "http://localhost/itnerd-git/scriptjes/warehousetype"
curl -k "http://localhost/itnerd-git/scriptjes/itemfingoodsmax"
curl -k "http://localhost/itnerd-git/scriptjes/itemmax"
curl -k "http://localhost/itnerd-git/scriptjes/productlist"
curl -k "http://localhost/itnerd-git/scriptjes/numberwatch_warehouse"
curl -k "http://localhost/itnerd-git/scriptjes/pos_invoice"
curl -k "http://localhost/itnerd-git/scriptjes/pos_invoicedetail"
curl -k "http://localhost/itnerd-git/scriptjes/shop"